### ISSUE TITLE
Error: No logs. Can't Read or Change Site's Data

### ISSUE THREAD

**Issue by jmctee** [michaelgoetze/LogDog#13]
Hi. Probably user error, but have not been able to collect logs while playing. During a game, see the above error in the LogDog Extension.

A screen grab of my options can be found [here](https://www.dropbox.com/s/6lnpmb35luyg432/logDogScreenshot1.png?dl=0).

And a screen grab of the game in play can be found [here](https://www.dropbox.com/s/1rl6bod8wzbewyo/logDogScreenshot2.png?dl=0).

Please let me know if you have any ideas what I am doing wrong. Running Chrome, Version 92.0.4515.159 (Official Build) (x86_64), on Mac OS X, 10.13.6

Thanks for your time, the extension looks very cool.

**Comment by michaelgoetze** [comment]
Hi! 
Could you try installing from the github source? 

>To install this extension, download this repository as ZIP-file and extract the content anywhere on your PC, where it will stay (So the Desktop is maybe not the best place). Use Chrome and go to the adress:

>chrome://extensions

> and activate developer mode in the top right corner of this window. Then use the button "load unpacked extension" and navigate to the unzipped folder that contains all the extension files and select this folder. Make sure that the extension is active (small slider switch) and you should see the LogDog-icon next to your adress bar (it might be hidden, decrease the size of your adress bar to see hidden extensions.

**Comment by jmctee** [comment]
Thanks. I’ll give this a shot. Won’t be able to test until this evening, will let you know how it goes.

**Comment by jmctee** [comment]
Hello,

Followed these instructions to install the extension, then tested on dominion.games. Worked! Thanks for your help.

I am fine using the plugin like this, but if there is anything you'd like me to do to debug installing from the Chrome store, just let me know, I'm willing to help.

Great tool, really appreciate you building it!

Thanks and take care,

Joe

**Comment by michaelgoetze** [comment]
I think the problem is already solved. I just didn't manage to upload the newest version of LogDog to the Chrome webstore. Google now requires a privacy policy document which had no time to create and put online until now. Just glad it works with the newest version from the repository.
